# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'leyou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for leyou
  pod ‘Onboard’
  pod ‘DZNEmptyDataSet’
  pod ‘SVProgressHUD’
  pod ‘Masonry’
  pod ‘MJRefresh’
  pod ‘UITableView+FDTemplateLayoutCell’
  pod ‘SDCycleScrollView’
  pod ‘WMPageController’
  pod ‘AVOSCloud’
  pod ‘YYImage’
  pod ‘YYWebImage’
  pod ‘YYKeyboardManager’
end
